### ISSUE TITLE
Unclear shop id configuration.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/ConnectionsBundle#105]
Now used shop ids must be defined in parameters like this
```yaml
parameters:
    shop_ids:
        - 0
```
But if configuration is not provided it default to shop ids and then `ongr:sync:provide` console command puts data in not suffixed table but `SyncExecuteSourceEventListener` never expect data in tables without suffix.

So the problem is that default configuration (no configuration) is invalid and it will not be clear what is wrong and i suggest either throwing errors if configuration is missing or changing default to something that works.

**Comment by trylika** [comment]
Related to #102

**Comment by GrandLTU** [comment]
Also adding to this issue currently there is several ways to configure shop id and its not clear what that does
example:
```yaml
ongr_connections:
    shops:
        - shop_id: 0
    active_shop: 0
```
And one from connector:
```yaml
ongr_magento:
    shop: 0
```
