### ISSUE TITLE
Bad example in sync storage configuration

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/ConnectionsBundle#77]
https://github.com/ongr-io/ConnectionsBundle/blob/master/Resources/doc/sync_storage.rst

``` yml
ongr_connections:
    sync_storage:
        mysql:
            connection: default
            table_name: ongr_sync_storage
``` 
should be

``` yml
ongr_connections:
    sync:
        sync_storage:
            mysql:
                connection: default
                table_name: ongr_sync_storage
```
